//Новости
export const SET_NEWS = 'GT/NEWS/SET_NEWS';
export const CHANGE_NEWS_ITEM = 'GT/NEWS/CHANGE_NEWS_ITEM';
export const SET_NEWS_ITEM = 'GT/NEWS/SET_NEWS_ITEM';
export const IS_ALL_NEWS = 'GT/NEWS/IS_ALL_NEWS';
export const SET_CURRENT_NEWS_ID = 'GT/NEWS/SET_CURRENT_NEWS_ID';
export const SET_NEWS_COUNT = 'GT/NEWS/SET_NEWS_COUNT';
export const SET_DEFAULT_NEWS = 'GT/NEWS/SET_DEFAULT_NEWS';
export const SET_PROJECT_ID_FOR_REDIRECT = 'GT/NEWS/SET_PROJECT_ID_FOR_REDIRECT';

//Проекты
export const SET_PROJECTS = 'GT/PRJ/SET_PROJECTS';
export const SET_PROJECT = 'GT/PRJ/SET_PROJECT';
export const CHANGE_PROJECTS_ITEM = 'GT/PRJ/CHANGE_PROJECTS_ITEM';
export const SET_PROJECTS_ITEM = 'GT/PRJ/SET_PROJECTS_ITEM';
export const IS_ALL_PROJECTS = 'GT/PRJ/IS_ALL_PROJECTS';
export const SET_PROJECTS_COUNT = 'GT/PRJ/SET_PROJECTS_COUNT';
export const LOAD_PROJECTS  ='GT/PRJ/LOAD_PROJECTS';
export const SET_ID = 'GT/PRJ/SET_ID';
export const LOAD_ALBUMS  ='GT/PRJ/LOAD_ALBUMS';
export const SET_DEFAULT_PROJECT = 'GT/PRJ/SET_DEFAULT_PROJECT';
export const SET_PROJECTS_PHOTOS = 'GT/PRJ/SET_PROJECTS_PHOTOS';
export const SET_URL_TO_PROJECTS_PHOTOS = 'GT/PRJ/SET_URL_TO_PROJECTS_PHOTOS';
export const SET_ALBUM_ID_FOR_REDIRECT = 'GT/PRJ/SET_ALBUM_ID_FOR_REDIRECT';

//Объявления
export const SET_JOBS = 'SET_JOBS';
export const CHANGE_JOBS_ITEM = 'CHANGE_JOBS_ITEM';
export const SET_JOBS_ITEM = 'SET_JOBS_ITEM';
export const IS_ALL_JOBS = 'IS_ALL_JOBS';
export const SET_CURRENT_JOBS_ID = 'SET_CURRENT_JOBS_ID';
export const SET_JOBS_COUNT = 'SET_JOBS_COUNT';
export const SET_DEFAULT_JOB = 'SET_DEFAULT_JOB';


//Альбомы и фото
export const SET_PHOTO_ALBUMS = 'SET_PHOTO_ALBUMS';
export const SET_PHOTOS = 'SET_PHOTOS';
export const SET_PHOTO = 'SET_PHOTO';
export const SET_URL_TO_ALBUMS = 'SET_URL_TO_ALBUMS';
export const SET_URL_TO_PHOTOS = 'SET_URL_TO_PHOTOS';

//Контакты
export const SET_CONTACTS = 'SET_CONTACTS';
export const SET_IS_CHANGED_CONTACTS = 'SET_IS_CHANGED_CONTACTS';
export const SET_DEFAULT_CONTACTS = 'SET_DEFAULT_CONTACTS';

//О Нас
export const SET_ABOUT = 'SET_ABOUT';
export const SET_IS_CHANGED_ABOUT = 'SET_IS_CHANGED_ABOUT';
export const SET_DEFAULT_ABOUT = 'SET_DEFAULT_ABOUT';

//Пользователи
export const SET_USERS = 'SET_USERS';
export const CHANGE_USERS_ITEM = 'CHANGE_USERS_ITEM';
export const SET_USERS_ITEM = 'SET_USERS_ITEM';
export const IS_ALL_USERS = 'IS_ALL_USERS';
export const SET_CURRENT_USERS_ID = 'SET_CURRENT_USERS_ID';
export const SET_USERS_COUNT = 'SET_USERS_COUNT';
export const SET_IS_USERS = 'SET_IS_USERS';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const SET_DEFAULT_USER = 'SET_DEFAULT_USER';
export const SET_ADMIN_ROOT_COUNT = 'SET_ADMIN_ROOT_COUNT';
export const IS_ADMIN_ROOT_COUNT = 'IS_ADMIN_ROOT_COUNT';

/////
export const IS_CLICKED = 'IS_CLICKED';
export const SET_URL = 'SET_URL';
export const SET_ADMIN_MODE = 'SET_ADMIN_MODE';








