//Новости
export const SET_NEWS = 'GT/NEWS/SET_NEWS';
export const CHANGE_NEWS_ITEM = 'GT/NEWS/CHANGE_NEWS_ITEM';
export const SET_NEWS_ITEM = 'GT/NEWS/SET_NEWS_ITEM';
export const IS_ALL_NEWS = 'GT/NEWS/IS_ALL_NEWS';
export const SET_CURRENT_NEWS_ID = 'GT/NEWS/SET_CURRENT_NEWS_ID';
export const SET_NEWS_COUNT = 'GT/NEWS/SET_NEWS_COUNT';
export const SET_DEFAULT_NEWS = 'GT/NEWS/SET_DEFAULT_NEWS';
export const SET_PROJECT_ID_FOR_REDIRECT = 'GT/NEWS/SET_PROJECT_ID_FOR_REDIRECT';

//Проекты
export const SET_PROJECTS = 'GT/PRJ/SET_PROJECTS';
export const SET_PROJECT = 'GT/PRJ/SET_PROJECT';
export const CHANGE_PROJECTS_ITEM = 'GT/PRJ/CHANGE_PROJECTS_ITEM';
export const SET_PROJECTS_ITEM = 'GT/PRJ/SET_PROJECTS_ITEM';
export const IS_ALL_PROJECTS = 'GT/PRJ/IS_ALL_PROJECTS';
export const SET_PROJECTS_COUNT = 'GT/PRJ/SET_PROJECTS_COUNT';
export const LOAD_PROJECTS  ='GT/PRJ/LOAD_PROJECTS';
export const SET_ID = 'GT/PRJ/SET_ID';
export const LOAD_ALBUMS  ='GT/PRJ/LOAD_ALBUMS';
export const SET_DEFAULT_PROJECT = 'GT/PRJ/SET_DEFAULT_PROJECT';
export const SET_PROJECTS_PHOTOS = 'GT/PRJ/SET_PROJECTS_PHOTOS';
export const SET_URL_TO_PROJECTS_PHOTOS = 'GT/PRJ/SET_URL_TO_PROJECTS_PHOTOS';
export const SET_ALBUM_ID_FOR_REDIRECT = 'GT/PRJ/SET_ALBUM_ID_FOR_REDIRECT';
export const SET_CURRENT_PROJECT_ID = 'GT/PRJ/SET_CURRENT_PROJECT_ID';

//Объявления
export const SET_JOBS = 'GT/JOB/SET_JOBS';
export const CHANGE_JOBS_ITEM = 'GT/JOB/CHANGE_JOBS_ITEM';
export const SET_JOBS_ITEM = 'GT/JOB/SET_JOBS_ITEM';
export const IS_ALL_JOBS = 'GT/JOB/IS_ALL_JOBS';
export const SET_CURRENT_JOBS_ID = 'GT/JOB/SET_CURRENT_JOBS_ID';
export const SET_JOBS_COUNT = 'GT/JOB/SET_JOBS_COUNT';
export const SET_DEFAULT_JOB = 'GT/JOB/SET_DEFAULT_JOB';


//Альбомы и фото
export const SET_PHOTO_ALBUMS = 'GT/PHOTOS/SET_PHOTO_ALBUMS';
export const SET_PHOTOS = 'GT/PHOTOS/SET_PHOTOS';
export const SET_URL_TO_ALBUMS = 'GT/PHOTOS/SET_URL_TO_ALBUMS';
export const SET_URL_TO_PHOTOS = 'GT/PHOTOS/SET_URL_TO_PHOTOS';
export const IS_CLICKED = 'GT/PHOTOS/IS_CLICKED';
export const SET_URL = 'GT/PHOTOS/SET_URL';

//Контакты
export const SET_CONTACTS = 'GT/CS/SET_CONTACTS';
export const SET_IS_CHANGED_CONTACTS = 'GT/CS/SET_IS_CHANGED_CONTACTS';
export const SET_DEFAULT_CONTACTS = 'GT/CS/SET_DEFAULT_CONTACTS';

//О Нас
export const SET_ABOUT = 'GT/ABOUT/SET_ABOUT';
export const SET_IS_CHANGED_ABOUT = 'GT/ABOUT/SET_IS_CHANGED_ABOUT';
export const SET_DEFAULT_ABOUT = 'GT/ABOUT/SET_DEFAULT_ABOUT';

//Пользователи
export const SET_USERS = 'GT/US/SET_USERS';
export const CHANGE_USERS_ITEM = 'GT/US/CHANGE_USERS_ITEM';
export const SET_USERS_ITEM = 'GT/US/SET_USERS_ITEM';
export const IS_ALL_USERS = 'GT/US/IS_ALL_USERS';
export const SET_CURRENT_USERS_ID = 'GT/US/SET_CURRENT_USERS_ID';
export const SET_USERS_COUNT = 'GT/US/SET_USERS_COUNT';
export const SET_IS_USERS = 'GT/US/SET_IS_USERS';
export const CREATE_USER_SUCCESS = 'GT/US/CREATE_USER_SUCCESS';
export const SET_DEFAULT_USER = 'GT/US/SET_DEFAULT_USER';
export const SET_ADMIN_ROOT_COUNT = 'GT/US/SET_ADMIN_ROOT_COUNT';
export const IS_ADMIN_ROOT_COUNT = 'GT/US/IS_ADMIN_ROOT_COUNT';

//Авторизация
export const SET_ADMIN_MODE = 'GT/AUTH/SET_ADMIN_MODE';








